# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_auto_20160224_0145'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('review', models.TextField(blank=True)),
                ('stars', models.PositiveSmallIntegerField()),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_ratings', to='hub.UserProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TechRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('review', models.TextField(blank=True)),
                ('stars', models.PositiveSmallIntegerField()),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_ratings', to='hub.UserProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='grading',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='grading',
            name='grader',
        ),
        migrations.RemoveField(
            model_name='grading',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='source',
        ),
        migrations.RemoveField(
            model_name='providerrating',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='providerrating',
            name='source',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='source',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='problem',
        ),
        migrations.AddField(
            model_name='resource',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Grading',
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
        migrations.DeleteModel(
            name='ProviderRating',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='Solution',
        ),
        migrations.AddField(
            model_name='techrating',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_ratings', to='hub.Resource'),
        ),
        migrations.AddField(
            model_name='tag',
            name='resources',
            field=models.ManyToManyField(related_name='tags', to='hub.Resource'),
        ),
        migrations.AddField(
            model_name='goodrating',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_ratings', to='hub.Resource'),
        ),
    ]
