# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_auto_20160224_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='learning_style',
            field=models.CharField(choices=[(0, 'Video'), (1, 'Wiki'), (2, 'Slides'), (3, 'Lecture'), (4, 'Course'), (5, 'Research Paper'), (6, 'PDF'), (7, 'Problem Set')], default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[(0, 'Video'), (1, 'Wiki'), (2, 'Slides'), (3, 'Lecture'), (4, 'Course'), (5, 'Research Paper'), (6, 'PDF'), (7, 'Problem Set')], default=0, max_length=30),
        ),
    ]
