# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_auto_20160224_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.IntegerField(choices=[(1, 'Video'), (2, 'Wiki'), (3, 'Slides'), (4, 'Lecture'), (5, 'Course'), (6, 'Research Paper'), (7, 'PDF'), (8, 'Problem Set')], default=1, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='learning_style',
            field=models.CharField(choices=[(1, 'Video'), (2, 'Wiki'), (3, 'Slides'), (4, 'Lecture'), (5, 'Course'), (6, 'Research Paper'), (7, 'PDF'), (8, 'Problem Set')], default=1, max_length=30),
        ),
    ]
