# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_auto_20160225_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='length',
            field=models.IntegerField(blank=True, null=True, verbose_name='Length (min)'),
        ),
        migrations.AlterField(
            model_name='goodrating',
            name='review',
            field=models.TextField(blank=True, verbose_name='Review'),
        ),
        migrations.AlterField(
            model_name='goodrating',
            name='stars',
            field=models.PositiveSmallIntegerField(verbose_name='Stars'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=2000, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=500, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='url',
            field=models.CharField(max_length=250, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.CharField(max_length=250, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Views'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='techrating',
            name='review',
            field=models.TextField(blank=True, verbose_name='Review'),
        ),
        migrations.AlterField(
            model_name='techrating',
            name='stars',
            field=models.PositiveSmallIntegerField(verbose_name='Stars'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='topicset',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='topicset',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='learning_style',
            field=models.CharField(choices=[(1, 'Video'), (2, 'Wiki'), (3, 'Slides'), (4, 'Lecture'), (5, 'Course'), (6, 'Research Paper'), (7, 'PDF'), (8, 'Problem Set')], default=1, max_length=30, verbose_name='Learning Style'),
        ),
    ]
